package com.otplesssdk.otp.models

enum class OtpErrorReason {
    SMS_START_FAILED,
    SMS_TIMEOUT,
    SMS_OTP_NOT_FOUND,
    SMS_RETRIEVER_ERROR,
    SMS_PLAY_SERVICES_UNAVAILABLE,
    WHATSAPP_NOT_INSTALLED,
    WHATSAPP_HANDSHAKE_FAILED,
    WHATSAPP_TIMEOUT,
    WHATSAPP_OTP_NOT_FOUND,
    WHATSAPP_OTP_ERROR
}
