rootProject.name = "sna-sdk-android"
include ':utils-sdk'
include ':sna-sdk'
include ':otp-sdk'
include ':app'
project(':utils-sdk').projectDir = new File('utils-sdk')
project(':sna-sdk').projectDir = new File('sna-sdk')
project(':otp-sdk').projectDir = new File('otp-sdk')
project(':app').projectDir = new File('app')
